name: Publish
on:
  push:
    branches:
      - "main"  # publish only on the main branch

concurrency: ${{ github.workflow }}-${{ github.ref }}  # ensures that the two publish workflows cannot be happening at the same time

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4  # checks out the repository
      - uses: pnpm/action-setup@v3  # sets up pnpm
        with:
          version: 7
      - uses: actions/setup-node@v4  # sets up node
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile  # install with a frozen lockfile
      - name: Create Release Pull Request or Publish  # this is our last step
        id: changesets
        uses: changesets/action@v1  # uses the changesets action
        with:
          publish: pnpm run release  # then runs the build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.BILLY}}